# Generated by Django 4.1.3 on 2022-12-15 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_article_is_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='is_delete',
            new_name='is_deleted',
        ),
    ]
